config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  # resources :songs, :playlists, :users

  resources :users, only: [:create, :show, :edit, :update, :destroy] do
    get 'playlists/search_by_mood', to: 'playlists#search_by_mood'
    resources :playlists, only: [:create, :edit, :show, :destroy] do
      post 'search', to: 'playlists#search'
      resources :playlist_songs
    end
  end

  get '/login', to: 'users#login'
  post '/login', to: 'users#post_login'

  get '/signup', to: 'users#signup'
  post '/signup', to: 'users#create'

  post '/logout', to: 'users#logout'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :playlists
  has_many :playlist_songs, through: :playlists

  validates :username, :first_name, :last_name, :email , :password, :password_confirmation, presence: true
  validates :username, uniqueness: true
    validates :email , format: { with: /\A\S+@.+\.\S+\z/ } #Email must conform to email standards
    validates :username, format: { with: /[a-zA-Z0-9]{0,15}/ } #Username must have no special characers and be at most 15 characters long
    validates :password, format: { with: /(?=.*[a-zA-Z])(?=.*[0-9]).{7,}/ } #Password must have at least 1 number, 1 special character and be at least 7 characters long
  has_secure_password


  def authenticate(password)
    salt = password_digest[0..28]
    hashed = BCrypt::Engine::hash_secret(password, salt)
      if hashed == self.password_digest
        true
      else
        nil
      end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :call_login?, only: [:show]
  before_action :user_login?, only: [:edit]

  def login
  end

  def post_login
    @user = User.find_by_username(params[:user][:username])
    if @user == nil
      render :login
    elsif @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :login
    end
  end

  def signup
    @user = User.new
  end

  def create
    if params[:user][:password] != params[:user][:password_confirmation]
      render :signup
    else
      @user = User.new(new_user_params)
      if @user.valid?
        @user.save
        session[:user_id] = @user.id
        redirect_to @user
      else
        render :signup
      end
    end
  end

  def show #/users/1
    @user = User.find(params[:id])
    if session[:user_id] == @user.id
      @playlist = Playlist.new
      @owner_homepage  = true
    else
      @owner_homepage = false
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to '/'
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    @user.update(update_user_params)
    if @user.valid?
      redirect_to @user
    else
      render :edit
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to '/'
  end


private

  def update_user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation )
  end

  def new_user_params
    params.require(:user).permit(:username,:first_name,:last_name, :email, :password, :password_confirmation)
  end

  def call_login?
    if helpers.login? == false
      redirect_to '/'
    end
  end

  def user_login?
    @user = User.find(params[:id])
    if session[:user_id] != @user.id
      redirect_to user_path(@user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
<%=f.label :first_name %>
<%=f.text_field :first_name %>
<%= f.label :last_name %>
<%=f.text_field :last_name %>
<%=f.label :email %>
<%=f.text_field :email %>
<%=f.label :password %>
<%=f.password_field :password %>
<%=f.label :password_confirmation %>
<%=f.password_field :password_confirmation %>
<%=f.submit %>
<% end %>


<%= button_to "Delete User", @user, :method => :delete %>

app/views/users/login.html.erb
<h1>Login Sadboi</h1>

<%= form_tag ({controller: 'users', action: 'post_login', method: 'post'}) do %>
<label>UserName</label>
<%= text_field_tag :'user[username]' %>
<label>Password</label>
<%= password_field_tag :'user[password]' %>
<%= submit_tag "Log In" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username.capitalize + "'s" %> Playlists</h1>
<ul>
<% @user.playlists.each do |playlist|%>
  <li><%= link_to playlist.title, user_playlist_path(@user, playlist) %></li>
<% end %>
</ul>

<% if @owner_homepage %>
<h1>Create a new playlist</h1>
  <%= form_tag(user_playlists_path(@user), method: :post) do %>
  <label>Title</label>
  <%= text_field_tag :title %>
  <%= submit_tag 'Create a Playlist' %>
  <% end %>

<br>
  <%= button_to 'Delete User Account', @user, method: :delete %>
<% end %>

app/views/users/signup.html.erb
<h1>Signup New Sadboi</h1>
<%= form_tag('/signup', method: :post) do  %>

<br>cannot contain any special characters<br>
<%= label_tag "Enter New Username" %>
<%= text_field_tag :'[user]username'%><br>

<br>must contain at least 1 number, 1 special character, and be at least 7 characers long<br>
<%= label_tag "Enter Password" %>
<%= password_field_tag :'[user]password'%>

<%= label_tag "Confirm Password" %>
<%= password_field_tag :'[user]password_confirmation'%><br>
<%= label_tag "Enter First Name" %>
<%= text_field_tag :'[user]first_name'%><br>
<%= label_tag "Enter Last Name" %>
<%= text_field_tag :'[user]last_name'%><br>
<%= label_tag "Enter Email address" %>
<%= text_field_tag :'[user]email'%><br>
<%= submit_tag "Sign up" %>
<% end %>