config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  # resources :songs, :playlists, :users

  resources :users, only: [:create, :show, :edit, :update, :destroy] do
    get 'playlists/search_by_mood', to: 'playlists#search_by_mood'
    resources :playlists, only: [:create, :edit, :show, :destroy] do
      post 'search', to: 'playlists#search'
      resources :playlist_songs
    end
  end

  get '/login', to: 'users#login'
  post '/login', to: 'users#post_login'

  get '/signup', to: 'users#signup'
  post '/signup', to: 'users#create'

  post '/logout', to: 'users#logout'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :playlist_songs
  validates :title, presence: true 

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :call_login?, only: [:show]


  def create
    @playlist = Playlist.new(title: params[:title], user_id: params[:user_id])
    # byebug
    if !@playlist.valid?
      redirect_to user_path(params[:user_id])
    else
      @playlist.save
      redirect_to edit_user_playlist_path(@playlist.user_id, @playlist)
    end

  end

  def edit
    @playlist = Playlist.find(params[:id])
  end

  def search
    #enter api stuff
    #once found, Song.find_or_create_by(the song)
    #create playlist_song with self.id and the song_id
    #prompt to enter mood? so a redirect_to a mood action?
    #once the song is added, we redirect_to the new page, which will have the search form and a button to stop adding songs
    Yt.configuration.api_key = "enter api key here"
    videoId = helpers.search_youtube(params[:song_and_artist])
      #take me to that temp song#show page
    song = Song.find_or_create_by(video_id: videoId)
    # byebug
    playlist_song = PlaylistSong.create(playlist_id: params[:playlist_id], song_id: song.id)
      redirect_to edit_user_playlist_playlist_song_path(user_id: params[:user_id], playlist_id: params[:playlist_id],id: playlist_song.id)

    #at this step, we route them to a page that just has the youtubevideo, they listen to the song, and then if
    #if they want to add it to their playlist, prompt them to set a mood, and then create PlaylistSong and go forward
    # video = Yt::Video.new id: videoId
    #
    # byebug
    # # if video.category_title != "Music"
    # #   redirect_to edit_user_playlist_path(params[:user_id], params[:id])
    # # end
    # redirect_to edit_user_playlist_path(params[:user_id], params[:id])
  end

  def show
    @playlist = Playlist.find(params[:id])
    # moods =  @playlist.playlist_songs.map do |ps|
    #     ps.mood
    #   end
    # @sadboi_rating = moods.inject{ |sum, el| sum + el }.to_f / moods.size

    if session[:user_id] == @playlist.user_id
      @owner_homepage  = true
    else
      @owner_homepage = false
    end
  end

  def search_by_mood
    @playlists = Playlist.where(mood: params[:mood])
  end

  def destroy
    playlist = Playlist.find(params[:id])
    playlist.destroy
    redirect_to user_path(params[:user_id])
  end

private
  def call_login?
    if helpers.login? == false
      redirect_to '/'
    end
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/edit.html.erb
<h1>Add Songs (sadboi only plz) to <%= @playlist.title %></h1>
<h3>Search for a song</h3>

<%= form_tag(user_playlist_search_path(@playlist.user_id, @playlist), method: :post) do %>
<%= text_field_tag :song_and_artist %>
<%= submit_tag "Search" %>
<% end %>

app/views/playlists/search_by_mood.html.erb
We found <%= pluralize(@playlists.size, "playlist") %> that fit your mood.

<% @playlists.each do |playlist| %>
  <ul>
    <li><%= link_to(playlist.title, user_playlist_path(playlist.user_id, playlist)) %> </li>
  </ul>
<% end %>

app/views/playlists/show.html.erb
<h1> Songs within your playlist</h1>

<h3> Sadboi rating: <%=@playlist.mood%></h3>
show all the videos of the playlist from the playlist songs
iterate through all the plasylistsong objects  b/c thats the only way we can access the Songs



<% @playlist.playlist_songs.each do |playlist_song| %>
  <% videoId = Song.find(playlist_song.song_id).video_id %>
  <% Yt.configuration.api_key = "AIzaSyDXvv8XUM7amNwkw_LD9lXwZUstWcVO0xw" %>
  <% video = Yt::Video.new id: videoId %>
  <h4><%= video.title %></h4> <br>
  <p><%= playlist_song.mood %></p>
  <iframe id="ytplayer" type="text/html" width="640" height="360"
  src="https://www.youtube.com/embed/<%=videoId%>"
  frameborder="0"></iframe>
<% end %>

<% if @owner_homepage %>
<%= button_to 'Add a song', edit_user_playlist_path(@playlist.user_id, @playlist), :method => :get %>
<%= button_to 'Delete This Playlist', user_playlist_path(@playlist.user_id, @playlist), method: :delete %>
<% end %>

<%= button_to "See which sadboi owns this playlist", user_path(@playlist.user_id), :method => :get %>