config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  # resources :songs, :playlists, :users

  resources :users, only: [:create, :show, :edit, :update, :destroy] do
    get 'playlists/search_by_mood', to: 'playlists#search_by_mood'
    resources :playlists, only: [:create, :edit, :show, :destroy] do
      post 'search', to: 'playlists#search'
      resources :playlist_songs
    end
  end

  get '/login', to: 'users#login'
  post '/login', to: 'users#post_login'

  get '/signup', to: 'users#signup'
  post '/signup', to: 'users#create'

  post '/logout', to: 'users#logout'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moodify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel=“stylesheet” href=“https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css“/>
    <script src=“https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js”></script>
    <script src=“https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js”></script>
    
  </head>

  <body>
    <nav>
      <% if session[:user_id] %>
        <h1>Look for a playlist that fits your sadboi levels</h1>
        <%= form_tag(user_playlists_search_by_mood_path(session[:user_id]), method: :get) do %>
        <%= label_tag "Enter your mood" %>
        <%= number_field_tag :mood, nil, min:1, max:10, placeholder: "Enter a Mood" %>
        <%= submit_tag "︻╦╤─" %>
        <% end %>
      <% end %>
    </nav>
    <%= yield %>

    <% if session[:user_id] %>
      <%= button_to 'Logout', action: 'logout', controller: 'users' %>
      <%= button_to 'Home', user_path(session[:user_id]), :method => :get %>

  <% end %>
  </body>
</html>